apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MONGODB_CONNECTION_URL: {{ .Values.secrets.mongodbUrl | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  GITHUB_TOKEN: {{ .Values.secrets.githubToken | quote }} 